version: '3.8'

services:
  gitlab:
    image: gitlab/gitlab-ce:17.5.1-ce.0  # 使用稳定版本而非latest
    container_name: gitlab-v4
    restart: unless-stopped
    hostname: 'gitlab.local'

    ports:
      # HTTP访问端口
      - "8080:80"
      # HTTPS访问端口（可选）
      - "8443:443"
      # SSH访问端口
      - "2223:22"
      # Container Registry端口
      - "5050:5050"

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        # 基础配置
        external_url 'http://192.168.0.127:8080'

        # SSH端口配置
        gitlab_rails['gitlab_shell_ssh_port'] = 2223

        # 初始root密码（首次登录后请修改）
        gitlab_rails['initial_root_password'] = 'GitLab@2024Admin!'

        # 时区设置
        gitlab_rails['time_zone'] = 'Asia/Shanghai'

        # 启用注册（可根据需要关闭）
        gitlab_rails['gitlab_signup_enabled'] = true

        # Container Registry配置
        registry_external_url 'http://192.168.0.127:5050'
        gitlab_rails['registry_enabled'] = true
        registry['enable'] = true

        # Git LFS支持
        gitlab_rails['lfs_enabled'] = true

        # 备份设置
        gitlab_rails['backup_keep_time'] = 604800  # 7天
        gitlab_rails['backup_path'] = '/var/opt/gitlab/backups'

        # 性能优化 - 简化配置，让GitLab自动调整
        # Puma（Web服务器）
        puma['worker_processes'] = 2
        puma['min_threads'] = 4
        puma['max_threads'] = 8

        # Sidekiq（后台任务）
        sidekiq['max_concurrency'] = 10

        # PostgreSQL基础优化
        postgresql['shared_buffers'] = '256MB'
        postgresql['max_connections'] = 200

        # 上传文件大小限制
        nginx['client_max_body_size'] = '500m'

        # 禁用不必要的组件以节省资源
        prometheus_monitoring['enable'] = false

        # GitLab Pages（可选，如不需要可注释掉）
        pages_external_url 'http://192.168.0.127:8090'
        gitlab_pages['enable'] = true
        gitlab_pages['listen_http'] = ['0.0.0.0:8090']

        # 日志轮转
        logging['svlogd_size'] = 100 * 1024 * 1024  # 100MB
        logging['svlogd_num'] = 5

    volumes:
      # 配置文件目录
      - ./gitlab-config:/etc/gitlab
      # 日志目录
      - ./gitlab-logs:/var/log/gitlab
      # 数据目录（包含Git仓库、上传文件等）
      - ./gitlab-data:/var/opt/gitlab
      # 备份目录（可选，独立挂载便于管理）
      - ./gitlab-backups:/var/opt/gitlab/backups

    # 健康检查
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost/-/health || exit 1"]
      interval: 60s
      timeout: 30s
      retries: 5
      start_period: 600s

    # 资源限制 - 根据你的服务器调整
    deploy:
      resources:
        limits:
          memory: 6G
          cpus: '4.0'
        reservations:
          memory: 4G
          cpus: '2.0'

    # 共享内存设置
    shm_size: 512m

# 可选：创建独立网络
networks:
  default:
    driver: bridge
    ipam:
      config:
        - subnet: 172.25.0.0/16